apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ensae-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/boalong/transformer-news-summarization-deployment.git
    targetRevision: adrien
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-aletellier
  syncPolicy:
    automated:
      selfHeal: true
